discord:
  token: ${DISCORD_TOKEN}

spring:
  jpa:
    open-in-view: false
rsl:
  heroes:
    arbiter: arbitre
    baron: baron
    belanor: belanor
    blind seer: prophetesse aveugle
    cruetraxa: cruetraxa
    gurgoh the augur: gurgoth l'augure
    hegemon: hegemon
    inithwe bloodtwin: inithwe doublesang
    ithos: ithos
    khoronar: khoronar
    krisk the ageless: krisk l'eternal
    raglin: raglin
    siphi the lost bride: siphi mariee egaree
    sir nicholas: sieur nicolas
    soulless: sans ame
    tormin the cold: tormin le froid
    turvold: turvold
    venus: venus
    warlord: seigneur de guerre
    wurlim frostking: wurlim roi du gel
    azure: azur
    baerdal fellhammer: beardal marteaucruel
    basher: cogneur
    battlesage: sageguerre
    broadmaw: largegeule
    cardinal: cardinale
    exemplar: archetype
    faceless: sans visage
    gala longbraids: gala longuenattes
    golden reaper: faucheuse doree
    lightsworn: devot de lumiere
    lua: lua
    madame serris: madame serris
    maneater: mangeur d'homme
    peydma: peydma
    psylar: psylar
    rowan: rowan
    seer: prophetesse
    skullcrown: couronnecrane
    skytouched shaman: chamane cieltouche
    suwai firstborn: suwai l'ainee
    towering titan: immense titan
    umbral enchantress: sombre enchanteresse
    warcaster: lance-guerre
    whisper: murmure
    amarantine skeleton: squelette pourpre
    arbalester: arbaletrier
    bellower: beugleur
    bloodhorn: cornesang
    bulwark: rempart
    centurion: centurion
    chevalier: chevalier
    coldheart: coeur-froid
    confessor: confesseuse
    daywalker: marcheur de jour
    doomscreech: crisseruine
    eviscerator: evisceratrice
    fellhound: chien cruel
    harrier: harrier
    haruspex: haruspex
    harvester: moissonneuse
    hollow: caverneux
    huntress: chasseresse
    ifrit: ifrit
    interceptor: intercepteur
    justiciar: justicier
    malbranche: malbranche
    marquis: marquis
    ox: yak
    pain keeper: garde-douleur
    painsmith: forgedouleur
    paragon: parangon
    ragemonger: pousserage
    reliquary tender: garde-reliquaire
    renegade: renegate
    retainer: domestique
    seducer: seducteur
    skirmisher: escarmoucheuse
    steadfast marshal: prevôt inebranlable
    stitched beast: bete suturee
    stoneskin: peaupierre
    vanguard: avant-garde
    veteran: veteran
    abbess: abbesse
    bad-el-kazar: bad-el-kazar
    basileus roanas: basileus roanas
    black knight: chevalier noir
    bloodgorged: gorgedesang
    brakus the shifter: brakus le metamorphe
    bystophus: bystophus
    candraphon: candraphon
    drexthar bloodtwin: drexthar doublesang
    elder skarg: skarg l'ancien
    errol: errol
    fu-shan: fu-shan
    minaya: minaya
    mountain king: roi de la montagne
    rhazin scarhide: rhazin scarhide
    robar: robar
    shirimani: shirimani
    skartorsis: skartosis
    vizier ovelis: vizier ovelis
    warchief: chef de guerre
    zavia: zavia
    alika: alika
    aothar: aothar
    basilisk: basilic
    bloodfeather: plumesang
    bonekeeper: gardiendos
    corpse collector: ramasse-cadavres
    defiled sinner: pecheur souille
    doompriest: pretresse de ruine
    erinyes: erinye
    hexia: hexia
    husk: cosse
    infernal baroness: baronne infernale
    kallia: kallia
    karam: karam
    lady etessa: dame etessa
    lich: liche
    luthiea: luthiea
    maeve: maeve
    mausoleum mage: mage de mausolee
    missionary: missionnaire
    nazana: nazana
    oathbound: lie par serment
    rearguard sergeant: arriere-garde
    reinbeast: renne bestial
    relickeeper: garde reliquaire
    ripper: eventreur
    romero: romero
    seneschal: senechal
    sepulcher sentinel: cerbere sepulcral
    shaman: chamane
    shatterbones: brisos
    sinesha: sinesha
    skullcrusher: ecrasecrane
    snorting thug: brute bougonne
    souldrinker: buveur d'ame
    spider: araignee
    teshada: teshada
    thenasil: thenasil
    torturehelm: heaumetorture
    ursine icecrusher: ours pile-glace
    ursine ironhide: ours peaudefer
    yaga the insatiable: yaga l'insatiable
    zargala: zargala
    acolyte: acolyte
    anointed: oint
    arcanist: arcaniste
    beast wrestler: dompte-betes
    bloodpainter: peintresang
    bogwalker: sculptemetal
    bombardier: bombardier
    chaplain: aumoniere
    courtier: courtisan
    fencer: escrimeuse
    gladiator: gladiateur
    goremask: masquegore
    grinner: rictus
    heiress: heritiere
    honor guard: garde d'honneur
    hurler: hurleur
    ironclad: cuirasse
    lamellar: mailles
    magister: magister
    magmablood: sangmagma
    mystic hand: main mystique
    ogryn jailer: geolier ogryn
    perforator: perforateur
    preserver: preservatrice
    sentinel: sentinelle
    skullsworn: portecrane
    slayer: assassin
    sorceress: magicienne
    steel bowyer: archere d'acier
    treefeller: abatarbre
    twinclaw disciple: disciple deuxgriffes
    warmaiden: vierge guerriere
    wretch: pauvre here
    admonitor: surveillant
    crusader: croise
    cultist: sectateur
    dead crusader: croise mort
    duelist: duelliste
    heartpiercer: perce-coeur
    hungerer: affameur
    incubus: incube
    intercessor: intercesseuse
    line infantry: infanterie de ligne
    oldbeard: vieillebarbe
    outlaw monk: moine hors-la-loi
    pilgrim: pelerin
    pit cur: batard d'arene
    pit fighter: guerrier d'arene
    redeemer: redemptrice
    sergeant: sergent
    skellag: squelette
    skullsquire: cranecuyer
    spiritwalker: marchesprit
    squire: ecuyer
    tracker: traqueur
    vulpine: vulpin
    axeman: fendeur
    preacher: predicatrice
    ranger: ranger
    sister militant: soeur militante
    altan: altan
    big ‘un: gros bill
    cillian the lucky: cillian le chanceux
    crypt-king graal: graal roi de crypte
    dracomorph: dracomorphe
    elenaril: elenaril
    foli: foli
    grohak the bloodied: grohak l'ensanglanté
    hakkorhn smashlord: hakkorhn fracapacha
    ignatius: ignatius
    lanakis the chosen: lanakis l'elue
    longbeard: longuebarbe
    lord champfort: lord champfort
    norog: norog
    prince kymar: prince kymar
    rae: rae
    roshcard the tower: roshcard la tour
    rotos the lost groom: rotos le marie egare
    scyl of the drakes: scyl des drakes
    sethallia: sethallia
    teela goremane: teela toisongore
    trunda giltmallet: trunda mailletdore
    tyrant ixlimor: tyran ixlimor
    war mother: mere de guerre
    adriel: adriel
    aina: aina
    alure: charme
    atur: atur
    canoness: chanoinesse
    captain temila: capitaine temila
    catacomb councilor: conseiller catacombe
    crypt witch: sorciere de crypte
    dark athel: sombre athel
    dark elhain: sombre elhain
    excruciator: tortureur
    flesh-tearer: dechire-chair
    frostbringer: perceneige
    gorgorab: gorgorab
    grimskin: peausombre
    grizzled jarl: jarl grisonnant
    hope: espoir
    hordin: hordin
    jarang: jarang
    jareg: jareg
    jotun: jotun
    juliana: juliana
    lordly legionary: noble legionnaire
    miscreated monster: monstre mal cree
    necrohunter: necrochasseur
    pitiless one: impitoyable
    royal guard: garde royal
    seeker: chercheur
    sikara: sikara
    tallia: tallia
    taurus: taurus
    tayrel: tayrel
    ultimate galek: galek supreme
    adjudicator: adjudicatrice
    apothecary: apothicaire
    athel: athel
    avenger: vengeresse
    banshee: banshee
    cataphract: cataphractaire
    chopper: hacheur
    coffin smasher: ecrase-cercueil
    crossbowman: arbaletrier
    cudgeler: batonneur
    deathchanter: chantemort
    diabolist: diaboliste
    elder: ancien
    elhain: elhain
    executioner: bourreau
    fleshmonger: louchebem
    fortress goon: sbire de forteresse
    frozen banshee: banshee gelee
    galek: galek
    gator: gator
    grandmaster: grand-maitre
    gravechill killer: tueur glacesombre
    graybeard: barbegrise
    grumbler: raleur
    hill nomad: nomade du tertre
    hospitaller: hospitaliere
    hound spawn: chien cruel
    judge: juge
    kael: kael
    magus: mage
    marked: marquee
    muckstalker: pistegadoue
    myrmidon: myrmidon
    pounder: assomeur
    rocktooth: dentpierre
    runic warder: gardien runique
    skink: scinque
    slitherbrute: brutondulante
    spikehead: tetepic
    stout axeman: fendeur robuste
    temptress: tentatrice
    theurgist: theurge
    tormentor: persecuteur
    valerie: valerie
    witness: temoin
    archer: archere
    aristocrat: aristocrate
    battle sister: soeur de combat
    brute: brute
    chemist: chimiste
    dervish: derviche
    frostskin: peau de givre
    hardscale: durecaille
    head taker: preneuse de tete
    lemure: lemur
    ritualist: ritualiste
    sharpshooter: tireur d'elite
    skinner: ecorcheur
    sniper: sniper
    stalker: harceleur
    stalwart: partisan
    warchanter: chanteguerre
    windtalker: parlevent
    word bearer: porte-parole
    death hound: chien du trepas
    deathknight: chevalier mortel
    lurker: rôdeur
    pikeman: piquier
    swordsman: epeiste
    thrall: vassal
    warboy: garcon guerrier
    yeoman: ribaud
    astralith: astralithe
    cupidus: cupidon
    duchess lilitu: duchesse lilitu
    ghostborn: nespectre
    harvest jack: jack le moisonneur
    lord shazar: lord shazar
    lugan the steadfast: lugan l'inebranlable
    lyssandra: lyssandra
    ma’shalled: ma'shalled
    martyr: martyre
    maulie tankard: maulie chope
    mortu-macaab: mortu-macaab
    nethril: nethril
    queen eva: reine eva
    richtoff the bold: richtoff l'effronte
    royal huntsman: chasseur royal
    septimus: septimus
    shamrock: trefle
    suzerain katonn: suzerain katonnn
    tomb lord: seigneur tombeau
    valkyrie: valkyrie
    yannica: yannica
    bushi: bushi
    cagebreaker: brisecage
    crimson helm: heaume incarnat
    deathless: immortelle
    delver: fouilleuse
    drake: drake
    fang cleric: pretre croc
    fenax: fenax
    galkut: galkut
    hellgazer: mirenfer
    high khatun: haute khatun
    jinglehunter: chasse-grelot
    jizoh: jizoh
    knight-errant: chevalier errant
    kytis: kytis
    luria: luria
    marksman: archer d'elite
    mistress of hymns: maitresse des hymnes
    occult brawler: castagneur occulte
    rock breaker: brise-pierre
    sandlashed survivor: survivant au sable
    stag knight: chevalier cerf
    steelskull: cranedacier
    terrorbeast: beteffroyable
    valla: valla
    vergis: vergis
    vrask: vrask
    warden: gardien
    woad-painted: guede-peinte
    zelotah: zelotah
    berserker: berseker
    bloodbraid: nattesang
    bone knight: chevalier d'os
    channeler: medium
    conquerer: conquerant
    corpulent cadaver: cadavre corpulent
    crimson slayer: tueuse incarnate
    flesheater: mangechair
    flinger: lanceur
    furystoker: soutierfurieux
    ghoulish ranger: ranger macabre
    gnarlhorn: cornenoueuse
    grappler: bagarreur
    guardian: gardien
    halberdier: hallebardier
    hatchet slinger: lance-hachettes
    hellfang: croc infernal
    hexweaver: tissesortilege
    hyria: hyrie
    judicator: magistrat
    madman: desaxe
    maiden: jouvencelle
    marquess: marquise
    master butcher: maitre boucher
    metalshaper: sculptemetal
    mother superior: mere superieure
    penitent: penitente
    raider: pillarde
    rotting mage: mage pourissant
    siegebreaker: brisesiege
    slasher: balafreur
    soulbond bowyer: archer chainame
    spirithost: hôtesprit
    templar: templier
    totem: totem
    wanderer: vagabond
    warpriest: pretresse de guerre
    armiger: armorie
    commander: commandeur
    crusher: broyeuse
    dhampir: dhampire
    elfguard: gardelfe
    fireblade: lamardente
    frontline warrior: guerrier de front
    herald: heraut
    jaeger: jaeger
    militia: milice
    outlander: etranger
    outrider: guide
    pitspawn: frai de mine
    satyr: satyre
    saurus: saurus
    shieldguard: gardebouclier
    slicer: trancheur
    thrasher: bastonneur
    throatcutter: coupegorge
    tunnel steward: intendant de tunnel
    vigilante: vigile
    vilespawn: vil rejeton
    zephyr sniper: sniper zephyr
    bandit: bandit
    bully: despote
    hellhound: chien de l'enfer
    knecht: serviteur
    magekiller: tueuse de mage
    novitiate: novice
    troglodyte: troglodyte