INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('1','Arbiter','Arbitre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arbitre-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('2','Bad el Kazar','Bad el Kazar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bad-el-kazar-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('3','Dracomorph','Dracomorphe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dracomorphe-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('4','Drexthar Bloodtwin','Drexthar Doublesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-drexthar-doublesang-drexthar-bloodtwin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('5','Duchess Lilitu','Duchesse Lilitu','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-duchesse-lilitu-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('6','Ithos','Ithos','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ithos-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('7','Krisk The Ageless','Krisk L Eternel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-krisk-leternel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('8','Prince Kymar','Prince Kymar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-prince-kymar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('9','Martyr','Martyre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-martyre-martyr-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('10','Ma Shalled','Ma Shalled','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mashalled-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('11','Nethril','Nethril','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nethril-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('12','Raglin','Raglin','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-raglin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('13','Rotos The Lost Groom','Rotos le Marié Egaré','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rotos-le-marie-egare-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('14','Sir Nicholas','Sieur Nicolas','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sieur-nicolas-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('15','Siphi The Lost Bride','Siphi Mariée Egarée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-siphi-mariee-egaree-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('16','Turvold','Turvold','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-turvold-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('17','Valkyrie','Valkyrie','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valkyrie-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('18','Venus','Venus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-venus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('19','Warlord','Seigneur de Guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-seigneur-de-guerre-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('20','Abbess','Abbesse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-abbesse-abbess-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('21','Altan','Altan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-altan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('22','Angar','Angar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-angar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('23','Belanor','Belanor','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-belanor-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('24','Blind Seer','Prophétesse Aveugle','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-prophetesse-aveugle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('25','Brakus The Shifter','Brakus le Métamorphe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brakus-le-metamorphe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('26','Royal Huntsman','Chasseur Royal','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chasseur-royal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('27','Cruetraxa','Cruetraxa','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cruetraxa-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('28','Cupidus','Cupidon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cupidon-cupidus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('29','Foli','Foli','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-foli-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('30','Fu-Shan','Fu-Shan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fu-shan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('31','Ignatius','Ignatius','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ignatius-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('32','Bloodgorged','Gorgédesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gorgedesang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('33','Big Un','Gros Bill','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gros-bill-big-un-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('34','Gurgoh Augur','Gurgoth l Augure','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gurgoth-laugure-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('35','Hegemon','Hégémon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hegemon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('36','Khoronar','Khoronar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-khoronar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('37','Longbeard','Longuebarbe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-longuebarbe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('38','Lyssandra','Lyssandra','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lyssandra-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('39','Maulie Tankard','Maulie Chope','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-maulie-chope-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('40','Ghostborn','Néspectre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-nespectre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('41','Rae','Rae','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rae-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('42','Rhazin Scarhide','Rhazin Peaumarquée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rhazin-peaumarquee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('43','Robar','Robar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-robar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('44','Roshcard The Tower','Roshcard la Tour','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roshcard-la-tour-roshcard-the-tower-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('45','Septimus','Septimus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-septimus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('46','Sethallia','Sethallia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sethallia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('47','Souless','Sans Ame','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sans-ame-soulless-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('48','Suzerain Katonn','Suzerain Katonn','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-suzerain-katonn-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('49','Tormin the Cold','Tormin le Froid','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tormin-le-froid-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('50','Shamrock','Shamrock','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-trefle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('51','Trunda Giltmallet','Trunda MailletDoré','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-trunda-mailletdore-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('52','Tyrant Ixlimor','Tyrant Ixlimor','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tyran-ixlimor-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('53','Vizier Ovelis','Vizier Ovelis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-vizir-ovelis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('54','Zavia','Zavia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zavia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('55','Astralith','Astralithe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-astralithe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('56','Baron','Baron','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-baron-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('57','Basileus Roanas','Basileus Roanas','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-basileus-roanas-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('58','Warchief','Chefdeguerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chefdeguerre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('59','Black Knight','Chevalier noir','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chevalier-noir-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('60','Cillian the Lucky','Cillian le Chanceux','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cillian-le-chanceux-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('61','Elenaril','Elénaril','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-elenaril-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('62','Errol','Errol','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-errol-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('63','Gurptuk Moss-Beard','Gurptuk Barbe-Mousse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gurptuk-barbe-mousse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('64','Hakkorhn Smashlord','Hakkorhn Fracapacha','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hakkorhn-fracapacha-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('65','Harvest Jack','Jack le Moissonneur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-jack-le-moissonneur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('66','Lanakis The Chosen','Lanakis l Élué','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lanakis-lelue-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('67','Lord Champfort','Lord champfort','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lord-champfort-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('68','Lord Shazar','Lord Shazar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lord-shazar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('69','Lugan the Steadfast','Lugan l Inébranlable ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lugan-linebranlable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('70','War Mother','Mère de Guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-mere-de-guerre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('71','Minaya','Minaya','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-minaya-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('72','Norog','Norog','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-norog-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('73','Queen Eva','Reine éva','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-reine-eva-queen-eva-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('74','Richtoff The Bold','Richtoff l’Effronté','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-richtoff-leffronte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('75','Scyl of the Drakes','Scyl des Drakes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-scyl-des-drakes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('76','Shirimani','Shirimani','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-shirimani-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('77','Elder Skarg','Skarg l Ancien','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-skarg-lancien-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('78','Skartorsis','Skartorsis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-skartorsis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('79','Tomb Lord','Seigneur Tombeau','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-seigneur-tombeau-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('80','Teela Goremane','Teela Toisongore','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-teela-toisongore-teela-goremane-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('81','Yannica','Yannica','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-yannica-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('82','Bystophus','Bystophus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bystophus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('83','Candraphon','Candraphon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-candraphon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('84','Mortu-Macaab','Mortu-Macaab','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mortu-macaab-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('85','Crypt King Graal','Graal Roi de Crypte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-graal-roi-de-crypte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('86','Grohak The Bloodied','Grohak l Ensanglanté','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-grohak-lensanglante-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('87','Mountain King','Roi de la montagne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-roi-de-la-montagne-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('88','Wurlim Frostking','Wurlim Roi du Gel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-wurlim-roi-du-gel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('89','Skull Lord Var-Gall','Lord Crâne Var-Gall','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lord-crane-var-gall-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('90','Inithwe Bloodtwin','Inithwe Doublesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-inithwe-doublesang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('91','Stag Knight','Chevalier Cerf','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chevalier-cerf-stag-knigh-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('92','Madame Serris','Madame Serris','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-madame-serris-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('93','Miscreated Monster','Monstre Mal Créé','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-monstre-mal-cree-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('94','Peydma','Peydma','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-peydma-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('95','Skullcrown','CouronneCrâne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-couronnecrane-skullcrown-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('96','Tayrel','Tayrel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tayrel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('97','Aothar','Aothar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-aothar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('98','Exemplar','Archétype','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-archetype-exemplar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('99','Rearguard Sergeant','Arrière-garde','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arriere-garde-rearguard-sergeant-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('100','Infernal Baroness','Baronne Infernale','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-baronne-infernale-infernal-baroness-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('101','Sepulcher Sentinel','Cerbère Sépulcral','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cerbere-sepulcral-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('102','Alure','Charme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-charme-alure-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('103','Seeker','Chercheur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chercheur-seeker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('104','Basher','Cogneur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cogneur-basher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('105','Steelskull','Crânedacier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cranedacier-steelskull-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('106','Lightsworn','Dévot de Lumière','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-devot-de-lumiere-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('107','Skullcrusher','ÉcraseCrâne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ecrasecrane-skullcrusher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('108','Golden Reaper','Faucheuse Dorée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-faucheuse-doree-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('109','Royal Guard','Garde Royal','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-royal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('110','Warden','Gardien','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gardien-warden-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('111','Gorgorab','Gorgorab','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gorgorab-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('112','Jareg','Jareg','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jareg-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('113','Juliana','Juliana','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-juliana-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('114','Lua','Lua','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lua-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('115','Maneater','Mangeur d Homme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mangeur-dhomme-maneater-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('116','Nazana','Nazana','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nazana-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('117','Doompriest','Prêtresse de ruine','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pretresse-de-ruine-doompriest-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('118','Reinbeast','Renne Bestial','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-renne-bestial-reinbeast-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('119','Romero','Roméro','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-romero-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('120','Battlesage','Sageguerre ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sageguerre-battlesage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('121','Sikara','Sikara','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sikara-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('122','Sinesha','Sinesha','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sinesha-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('123','Dark Elhain','Sombre Elhain','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sombre-elhain-dark-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('124','Umbral Enchantress','Sombre Enchanteresse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sombre-enchanteresse-umbreal-enchantress-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('125','Thenasil','Thénasil','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-thenasil-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('126','Vrask','Vrask','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vrask-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('127','Zargala','Zargala','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zargala-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('128','Zelotah','Zelotah','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zelotah-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('129','Adriel','Adriel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-adriel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('130','Spider','Araignée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-araignee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('131','Azure','Azur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-azur-azure-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('132','Baerdal Fellhammer','Baerdal Marteaucruel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-baerdal-marteaucruel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('133','Basilisk','Basilic','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-basilic-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('134','Shatterbones','Brisos','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brisos-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('135','Snorting Thug','Brute Bougonne','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('136','Souldrinker','Buveur d’âme','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('137','Bloodfeather','Plumesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-plumesang-bloodfeather-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('138','Cagebreaker','Brisecage','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('139','Rock Breaker','Brise-pierre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('140','Captain Temila','Capitaine Témila','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('141','Cardinal','Cardinale','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('142','Jinglehunter','Chasse-Grelot','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chasse-grelot-jinglehunter-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('143','Knight Errant','Chevalier Errant','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('144','Lady Etessa','Dame Etessa','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('145','Flesh Tearer','Déchire-Chair','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('146','Erinyes','Erinye','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('147','Fenax','Fenax','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-fenax-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('148','Gala Longbraids','Gala Longuenattes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gala-longuenattes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('149','Ultimate Galek','Galek Suprême','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galek-supreme-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('150','Galkut','Galkut','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galkut-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('151','Relickeeper','Garderelique','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garderelique-relickeeper-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('152','Grizzled Jarl','Grisonnant','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('153','High Khatun','Haute Khatun','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-haute-khatun-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('154','Crimson Helm','Heaume incarnat','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-heaume-incarnat-rimson-helm-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('155','Hordin','Hordin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('156','Towering Titan','Immense Titan','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('157','Deathless','Immortelle','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('158','Jarang','Jarang','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('159','Kallia','Kallia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kallia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('160','Karam','Karam','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-karam-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('161','Warcaster','Lance-guerre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('162','Lich','Liche','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('163','Oathbound','Lié par serment','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('164','Luria','Luria','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-luria-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('165','Lutheia','Luthiéa','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-luthiea-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('166','Mausoleum Mage','Mage de Mausolée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mage-de-mausolee-mausoleum-mage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('167','Mistress of Hymns','Maîtresse des Hymnes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-maitresse-des-hymnes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('168','Necrohunter','Nécrochasseur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-necrochasseur-necrohunter-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('169','Grimskin','Peausombre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('170','Defiled Sinner','Pécheur Souillé','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('171','Fang Cleric','Prêtre Croc','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('172','Psylar','Psylar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-psylar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('173','Rowan','Rowan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rowan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('174','Corpse Collector','Ramasse-Cadavres','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ramasse-cadavres-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('175','Crypt Witch','Sorcière de Crypte','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('176','Dark Athel','Sombre Athel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sombre-athel-dark-athel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('177','Sandlashed Survivor','Survivante au Sable','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('178','Suwai Firstborn','Suwaï l Aînée','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('179','Tallia','Tallia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tallia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('180','Excruciator','Tortureur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tortureur-excruciator-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('181','Valla','Valla','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valla-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('182','Vergis','Vergis','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('183','Yaga the Insatiable','Yaga l insatiable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yaga-linsatiable-yaga-the-insatiable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('184','Marksman','Archer d élite','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('185','Atur','Atur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('186','Terrorbeast','Bêteffroyable','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('187','Occult Brawler','Castagneur Occulte','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('188','Shaman','Chamane','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chamane-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('189','Catacomb Councilor','Conseiller Catacombe','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('190','Husk','Cosse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('191','Hope','Espoir','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-espoir-hope-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('192','Delver','Fouilleuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fouilleuse-delver-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('193','Bonekeeper','Gardiendos','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('194','Hexia','Hexia','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('195','Pitiless One','Impitoyable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-impitoyable-pitiless-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('196','Jizoh','Jizoh','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jizoh-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('197','Jotun','Jotun','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('198','Kytis','Kytis','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('199','Broadmaw','Largegueule','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('200','Missionary','Missionnaire','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('201','Whisper','Murmure','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-murmure-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('202','Lordly Legionary','Noble Légionnaire','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('203','Ursine Ironhide','Ours Peaudefer','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ours-peaudefer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('204','Ursine Icecrusher','Ours Pile-Glace','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('205','Frostbringer','Perceneige','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-perceneige-frostbringer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('206','Seer','Prophétesse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('207','Seneschal','Sénéchal','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('208','Aina','Aina','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('209','Alika','Alika','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('210','Bushi','Bushi','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('211','Skytouched Shaman','Chamane Cieltouché','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('212','Cannoness','Chanoinesse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('213','Drake','Drake','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-drake-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('214','Ripper','Eventreur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('215','Woad Painted','Guède-Peinte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-guede-peinte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('216','Torturehelm','Heaumetorture','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('217','Hellgazer','Mirenfer','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mirenfer-hellgazer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('218','Maeve','Maève','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-maeve-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('219','Faceless','Sans visage','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('220','Taurus','Taurus','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('221','Teshada','Téshada','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('222','Paragon','Parangon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-parangon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('223','Apothecary','Apothicaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-apothicaire-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('224','Bellower','Beugleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-beugleur-bellower-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('225','Kael','Kael','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kael-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('226','Coldheart','CoeurFroid','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-coeurfroid-coldheart-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('227','Reliquary Tender','Garde-Reliquaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-reliquaire-reliquary-tender-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('228','Warmaiden','Vierge guerrière','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vierge-guerriere-warmaiden-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('229','Athel','Athel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-athel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('230','Elhain','Elhain','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-elhain-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('231','Grappler','Bagarreur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('232','Frozen Banshee','Banshee Gelée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-banshee-gelee-frozen-banshee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('233','Executioner','Bourreau','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bourreau-executioner-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('234','Fellhound','Chien Cruel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chien-cruel-fellhound-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('235','Doomscreech','Crisseruine','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-crisseruine-doomscreech-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('236','Diabolist','Diaboliste','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-diaboliste-diabolist-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('237','Coffin Smasher','Écrase-Cercueil','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ecrase-cercueil-coffin-smasher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('238','Skirmisher','Escarmoucheuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('239','Painkeeper','Garde-Douleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-douleur-pain-keeper-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('240','Spirithost','Hôtesprit','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hotesprit-spirithost-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('241','Seducer','Séducteur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-seducteur-seducer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('242','Arcanist','Arcaniste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('243','Soulbond Bowyer','Archer Chaînâme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-archer-chainame-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('244','Vanguard','Avant-garde','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('245','Banshee','Banshee','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('246','Berserker','Berserker','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-berserker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('247','Hollow','Caverneux','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('248','Bone Knight','Chevalier d’Os ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('249','Conquerer','Conquérant','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-conquerant-conquerer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('250','Retainer','Domestique','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-domestique-retainer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('251','Galek','Galek','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galek-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('252','Gator','Gator','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('253','Ogryn Jailer','Géôlier Ogryn','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('254','Gladiator','Gladiateur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('255','Haruspex','Haruspex','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-haruspex-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('256','Heiress','Héritière','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-heritiere-heiress-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('257','Hyria','Hyrie','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('258','Judge','Juge','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('259','Fleshmonger','Louchébem','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-louchebem-fleshmonger-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('260','Mystic Hand','Main Mystique','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('261','Bogwalker','Marchemarais','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marchemarais-bogwalker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('262','Daywalker','Marcheur de jour','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marcheur-de-jour-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('263','Channeler','Médium','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('264','Mother Superior','Mère Supérieur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('265','Harvester','Moissonneuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-moissonneuse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('266','Hill Nomad','Nomade du Tertre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('267','Anointed','Oint','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('268','Penitent','Pénitente','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('269','Preserver','Préservatrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('270','Warpriest','Prêtresse de Guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pretresse-de-guerre-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('271','Grinner','Rictus','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('272','Metalshaper','Sculptemétal','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('273','Furystroker','SoutierFurieux','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('274','Templar','Templier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-templier-templar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('275','Hexweaver','Tissesortilège','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('276','Gravechill Killer','Tueur Glacetombe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tueur-glacetombe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('277','Crimson Slayer','Tueuse Incarnate','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tueuse-incarnate-crimson-slayer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('278','Valerie','Valérie','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valerie-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('279','Veteran','Vétéran','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('280','Adjudicator','Adjudicatrice','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-adjudicatrice-adjudicator-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('281','Elder','Ancien','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('282','Slayer','Assassin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('283','Pounder','Assommeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('284','Chaplain','Aumônière','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('285','Graybeard','Barbegrise','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-barbegrise-graybeard-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('286','Cudgeler','Bâtonneur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('287','Siegebreaker','Brisesiège','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('288','Slitherbrute','Brutondulante','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('289','Corpulent Cadaver','Cadavre Corpulent','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('290','Deathchanter','Chantemort','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('291','Chevalier','Chevalier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chevalier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('292','Confessor','Confesseuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('293','Gnarlhorn','Cornenoueuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('294','Courtier','Courtisan','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('295','Ironclad','Cuirassé','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('296','Rocktooth','Dentpierre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dentpierre-rocktooth-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('297','Twinclaw Disciple','Disciple Deuxgriffes','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('298','Eviscerator','Eviscératrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('299','Fencer','Escrimeuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('300','Stout Axeman','Fendeur Robuste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('301','Guardian','Gardien','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('302','Runic Warder','Gardien Runique','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('303','Chopper','Hacheur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('304','Halberdier','Hallebardier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('305','Hurler','Hurleur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('306','Ifrit','Ifrit','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('307','Flinger','Lanceur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lanceur-flinger-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('308','Magus','Mage','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mage-magus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('309','Rotting Mage','Mage Pourrissant','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('310','Sorceress','Magicienne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-magicienne-sorceress-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('311','Magister','Magister','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('312','Lameller','Mailles','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('313','Master Butcher','Maître Boucher','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('314','Marked','Marquée','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marquee-marked-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('315','Myrmidon','Myrmidon','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('316','Bloodbraid','Nattesang','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('317','Wretch','Pauvre Hère','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('318','Bloodpainter','Peintresang','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('319','Raider','Pillarde','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('320','Skullsworn','Portecrâne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-portecrane-skullsworn-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('321','Grumbler','Râleur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('322','Bulwark','Rempart','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rempart-bulwark-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('323','Renegade','Renégate','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-renegate-renegade-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('324','Skink','Scinque','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('325','Sentinel','Sentinelle','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('326','Amaratine Skeleton','Squelette pourpre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('327','Witness','Témoin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('328','Temptress','Tentatrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('329','Theurgist','Théurge','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('330','Totem','Totem','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('331','Wanderer','Vagabond','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('332','Avenger','Vengeresse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vengeresse-avenger-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('333','Ox','Yak','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('334','Treefeller','Abatarbre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('335','Acolyte','Acolyte','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('336','Arbalester','Arbalétrier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('337','Crossbowman','Arbaletrier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('338','Steel Bowyer','Archere d Acier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('339','Slasher','Balafreur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('340','Stitched Beast','Bête suturée ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('341','Bombardier','Bombardier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('342','Bloodhorn','Cornesang','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('343','Cataphract','Cataphractaire','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('344','Centurion','Centurion','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-centurion-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('345','Huntress','Chasseresse ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('346','Hellfang','Croc infernal ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('347','Madman','Désaxé','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('348','Beast Wrestler','Dompte-Betes','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('349','Painsmith','Forgedouleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-forgedouleur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('350','Honor Guard','Garde d Honneur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('351','Grandmaster','Grand-maitre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('352','Harrier','Harrier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('353','Hospitaller','Hospitaliere','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('354','Interceptor','Intercepteur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('355','Maiden','Jouvencelle','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('356','Judicator','Magistrat','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('357','Justiciar','Justicier ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('358','Flesheater','Mangechair','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mangechair-flesheater-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('359','Hatchet Slinger','Lance-hachettes ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('360','Fortress Goon','Sbire de Forteresse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('361','Marquess','Marquise','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marquise-marquess-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('362','Marquis','Marquis','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('363','Goremask','Masquegore','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-masquegore-goremask-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('364','Malbranche','Malbranche','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('365','Muckstalker','Pistegadoue','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pistegadoue-muckstalker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('366','Perforator','Perforateur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('367','Steadfast Marshall','Prévôt inébranlable','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('368','Stoneskin','Peaupierre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-peaupierre-stoneskin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('369','Tormenter','Persecuteur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('370','Ragemonger','Pousserage','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('371','Ghoulish Ranger','Ranger Macabre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('372','Houndspawn','Rejeton de Cabot','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rejeton-de-cabot-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('373','Magmablood','Sangmagma','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sangmagma-magmablood-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('374','Spikehead','Tetepic','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('375','Armiger','Armorie','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('376','Dhampire','Dhampire','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('377','Outlaw Monk','Moine Hors-la-loi ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-moine-hors-la-loi-monk-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('378','Saurus','Saurus','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('379','Shieldguard','Gardebouclier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('380','Skinner','Ecorcheur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('381','Zephyr Sniper','Sniper Zephyr ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('382','Archer','Archer','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('383','Crusader','Croise ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('384','Dervish','Derviche ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('385','Elfguard','Gardelfe','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('386','Fireblade','Lamardente ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('387','Ritualiste','Ritualiste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('388','Sergeant','Sergent ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('389','Skullsquire','Cranecuyer ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('390','Sniper','Sniper','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sniper-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('391','Spiritwalker','Marchesprit','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('392','Vigilante','Vigile','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('393','Aristocrate','Aristocrate','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('394','Commander','Commandeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('395','Duelist','Duelliste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('396','Herald','Heraut','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('397','Hungerer','Affameur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('398','Militia','Milice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('399','Outlander','Etranger','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('400','Outrider','Guide ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('401','Pilgrim','Pelerin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('402','Satyre','Satyre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('403','Skellag','Squelette ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('404','Vulpine','Vulpin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('405','Warchanter','Chanteguerre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('406','Windtalker','Parlevent','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('407','Word Bearer','Porte-Parole','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('408','Battle Sister','Soeur de Combat','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('409','Brute','Brute','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('410','Chemist','Chimiste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('411','Crusher','Broyeuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('412','Dead Crusader','Croise Mort','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('413','Frontline Warrior','Guerrier de Front','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('414','Hardscale','Durecaille','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('415','Intercessor','Intercesseuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('416','Jaeger','Jaeger','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('417','Line Infantry','Infanterie de Ligne','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('418','Pit Fighter','Guerrier d Arene','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('419','Pitspawn','Frai de Mine ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('420','Redeemer','Redemptrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('421','Squire','Ecuyer','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('422','Stalwart','Partisan','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('423','Tunnel Steward','Intendant de Tunnel','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('424','Vilespawn','Vil Rejeton','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('425','Admonitor','Surveillant','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('426','Cultist','Sectateur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('427','Frostskin','Peau de givre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('428','Head Taker','Preneuse de Tete','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('429','Heartpiercer','Perce-coeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('430','Incubus','Incube','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('431','Lemur','Lemur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('432','Oldbeard','Vieillebarbe','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('433','Pit Cur','Batard d Arene','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('434','Sharpshooter','Tireur d elite','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('435','Slicer','Trancheur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('436','Stalker','Harceleur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('437','Thrasher','Bastonneur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('438','Throatcutter','Coupegorge','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('439','Tracker','Traqueur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('440','Death Hound','Chien du Trépas','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('441','Yeoman','Ribaud','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('442','Sister Militant','Sœur Militante','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('443','Bandit','Bandit','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('444','Swordsman','Épéiste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('445','Pikeman','Piquier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('446','Deathknight','Chevalier Mortel','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('447','Novitiate','Novice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('448','Lurker','Rôdeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('449','Bully','Brute','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('450','Hellhound','Chien de l enfer','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('451','Axeman','Fendeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('452','Warboy','Garçon guerrier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('453','Preacher','Prédicatrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('454','Ranger','Ranger','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('455','Knecht','Serviteur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('456','Troglodyte','Troglodyte','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('457','Magekilleur','Tueuse de Mage','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name,url) VALUES ('458','Thrall','Vassal','AIE AIE AIE, pas encore de guide !');
